
package View;

import Controller.ControleEditarPerfil;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.JToggleButton;
import Model.Usuario;

public class EditarPerfil extends javax.swing.JFrame {

    private String user, nome, senha;
    
    public EditarPerfil() {
        initComponents();
    }

    public EditarPerfil(Usuario usuario){
        initComponents();
        user = usuario.getUsuario();
        nome = usuario.getNome();
        senha = usuario.getSenha();
        //System.out.println("usuario editar perfil" + usuario);
        c = new ControleEditarPerfil(this);
    }   
    
    public JToggleButton getBt_confirmar() {
        return bt_confirmar;
    }

    public void setBt_confirmar(JToggleButton bt_confirmar) {
        this.bt_confirmar = bt_confirmar;
    }

    public JLabel getLbl_aviso() {
        return lbl_aviso;
    }

    public void setLbl_aviso(JLabel lbl_aviso) {
        this.lbl_aviso = lbl_aviso;
    }

    public JLabel getLbl_nova_senha() {
        return lbl_nova_senha;
    }

    public void setLbl_nova_senha(JLabel lbl_nova_senha) {
        this.lbl_nova_senha = lbl_nova_senha;
    }

    public JLabel getLbl_novo_nome() {
        return lbl_novo_nome;
    }

    public void setLbl_novo_nome(JLabel lbl_novo_nome) {
        this.lbl_novo_nome = lbl_novo_nome;
    }

    public JLabel getLbl_novo_user() {
        return lbl_novo_user;
    }

    public void setLbl_novo_user(JLabel lbl_novo_user) {
        this.lbl_novo_user = lbl_novo_user;
    }

    public JLabel getLbl_senha_antiga() {
        return lbl_senha_antiga;
    }

    public void setLbl_senha_antiga(JLabel lbl_senha_antiga) {
        this.lbl_senha_antiga = lbl_senha_antiga;
    }

    public JLabel getLbl_voltar() {
        return lbl_voltar;
    }

    public void setLbl_voltar(JLabel lbl_voltar) {
        this.lbl_voltar = lbl_voltar;
    }

    public JTextField getTxt_nova_senha() {
        return txt_nova_senha;
    }

    public void setTxt_nova_senha(JTextField txt_nova_senha) {
        this.txt_nova_senha = txt_nova_senha;
    }

    public JTextField getTxt_novo_nome() {
        return txt_novo_nome;
    }

    public void setTxt_novo_nome(JTextField txt_novo_nome) {
        this.txt_novo_nome = txt_novo_nome;
    }

    public JTextField getTxt_novo_user() {
        return txt_novo_user;
    }

    public void setTxt_novo_user(JTextField txt_novo_user) {
        this.txt_novo_user = txt_novo_user;
    }

    public JTextField getTxt_senha_antiga() {
        return txt_senha_antiga;
    }

    public void setTxt_senha_antiga(JTextField txt_senha_antiga) {
        this.txt_senha_antiga = txt_senha_antiga;
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_novo_nome = new javax.swing.JLabel();
        lbl_novo_user = new javax.swing.JLabel();
        lbl_nova_senha = new javax.swing.JLabel();
        lbl_voltar = new javax.swing.JLabel();
        txt_novo_nome = new javax.swing.JTextField();
        bt_confirmar = new javax.swing.JToggleButton();
        lbl_aviso = new javax.swing.JLabel();
        lbl_senha_antiga = new javax.swing.JLabel();
        txt_novo_user = new javax.swing.JTextField();
        txt_senha_antiga = new javax.swing.JTextField();
        txt_nova_senha = new javax.swing.JTextField();
        lbl_editar_perfil = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Editar perfil");

        lbl_novo_nome.setText("novo nome:");

        lbl_novo_user.setText("novo user:");

        lbl_nova_senha.setText("nova senha:");

        lbl_voltar.setText("←");
        lbl_voltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_voltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_voltarMouseClicked(evt);
            }
        });

        txt_novo_nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_novo_nomeActionPerformed(evt);
            }
        });
        txt_novo_nome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_novo_nomeKeyPressed(evt);
            }
        });

        bt_confirmar.setText("Confirmar");
        bt_confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_confirmarActionPerformed(evt);
            }
        });

        lbl_aviso.setText("*caso não deseje fazer alguma modificação, deixe-a nula*");

        lbl_senha_antiga.setText("senha antiga:");

        txt_novo_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_novo_userActionPerformed(evt);
            }
        });
        txt_novo_user.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_novo_userKeyPressed(evt);
            }
        });

        txt_senha_antiga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_senha_antigaKeyPressed(evt);
            }
        });

        txt_nova_senha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_nova_senhaKeyPressed(evt);
            }
        });

        lbl_editar_perfil.setText("Editar perfil");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 54, Short.MAX_VALUE)
                .addComponent(lbl_aviso)
                .addGap(40, 40, 40))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_novo_nome)
                            .addComponent(lbl_novo_user)
                            .addComponent(lbl_nova_senha)
                            .addComponent(lbl_senha_antiga))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_nova_senha)
                            .addComponent(txt_senha_antiga)
                            .addComponent(txt_novo_nome, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_novo_user, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(lbl_voltar)
                        .addGap(141, 141, 141)
                        .addComponent(lbl_editar_perfil))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(bt_confirmar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_voltar)
                    .addComponent(lbl_editar_perfil))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(lbl_aviso)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_novo_user)
                    .addComponent(txt_novo_user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_novo_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_novo_nome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_nova_senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_nova_senha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_senha_antiga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_senha_antiga))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_confirmar)
                .addGap(59, 59, 59))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_confirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_confirmarActionPerformed
        // TODO add your handling code here:
        Usuario usuario = new Usuario(user, nome, senha);
        c.editarPerfil(usuario);
    }//GEN-LAST:event_bt_confirmarActionPerformed

    private void txt_novo_nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_novo_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_novo_nomeActionPerformed

    private void txt_novo_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_novo_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_novo_userActionPerformed

    private void lbl_voltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_voltarMouseClicked
        Usuario usuario = new Usuario(user, nome, senha); 
        c.redirectPerfil(usuario);
    }//GEN-LAST:event_lbl_voltarMouseClicked

    private void txt_novo_userKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_novo_userKeyPressed
        Usuario usuario = new Usuario(user, nome, senha); 
        if(evt.getKeyCode() == evt.VK_ENTER){
            c.editarPerfil(usuario);
        }
    }//GEN-LAST:event_txt_novo_userKeyPressed

    private void txt_novo_nomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_novo_nomeKeyPressed
        Usuario usuario = new Usuario(user, nome, senha); 
        if(evt.getKeyCode() == evt.VK_ENTER){
            c.editarPerfil(usuario);
        }
    }//GEN-LAST:event_txt_novo_nomeKeyPressed

    private void txt_nova_senhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nova_senhaKeyPressed
        Usuario usuario = new Usuario(user, nome, senha); 
        if(evt.getKeyCode() == evt.VK_ENTER){
            c.editarPerfil(usuario);
        }
    }//GEN-LAST:event_txt_nova_senhaKeyPressed

    private void txt_senha_antigaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_senha_antigaKeyPressed
        Usuario usuario = new Usuario(user, nome, senha); 
        if(evt.getKeyCode() == evt.VK_ENTER){
            c.editarPerfil(usuario);
        }
    }//GEN-LAST:event_txt_senha_antigaKeyPressed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(EditarPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(EditarPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(EditarPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(EditarPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new EditarPerfil().setVisible(true);
//            }
//        });
//    }

    private ControleEditarPerfil c;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton bt_confirmar;
    private javax.swing.JLabel lbl_aviso;
    private javax.swing.JLabel lbl_editar_perfil;
    private javax.swing.JLabel lbl_nova_senha;
    private javax.swing.JLabel lbl_novo_nome;
    private javax.swing.JLabel lbl_novo_user;
    private javax.swing.JLabel lbl_senha_antiga;
    private javax.swing.JLabel lbl_voltar;
    private javax.swing.JTextField txt_nova_senha;
    private javax.swing.JTextField txt_novo_nome;
    private javax.swing.JTextField txt_novo_user;
    private javax.swing.JTextField txt_senha_antiga;
    // End of variables declaration//GEN-END:variables
}
