
package View;

import java.awt.Choice;
import javax.swing.JButton;
import javax.swing.JCheckBoxMenuItem;
import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JRadioButtonMenuItem;
import javax.swing.JTextField;
import Model.Usuario;
import Controller.ControleHome;
import javax.swing.JComboBox;
import javax.swing.JTable;


import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.*;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableCellEditor;








public class Home extends javax.swing.JFrame {

    private String nome, senha, user;
        
    public Home() {
        initComponents();
        c = new ControleHome(this);

    }

    public Home(Usuario usuario) {
        initComponents();
        user = usuario.getUsuario();
        nome = usuario.getNome();
        lbl_nome.setText(nome);
        senha = usuario.getSenha();
        c = new ControleHome(this);
    }
    

    public JButton getBt_buscar() {
        return bt_buscar;
    }

    public void setBt_buscar(JButton bt_buscar) {
        this.bt_buscar = bt_buscar;
    }

    public JCheckBoxMenuItem getjCheckBoxMenuItem1() {
        return jCheckBoxMenuItem1;
    }

    public void setjCheckBoxMenuItem1(JCheckBoxMenuItem jCheckBoxMenuItem1) {
        this.jCheckBoxMenuItem1 = jCheckBoxMenuItem1;
    }

    public JMenu getjMenu1() {
        return jMenu1;
    }

    public void setjMenu1(JMenu jMenu1) {
        this.jMenu1 = jMenu1;
    }

    public JRadioButtonMenuItem getjRadioButtonMenuItem1() {
        return jRadioButtonMenuItem1;
    }

    public void setjRadioButtonMenuItem1(JRadioButtonMenuItem jRadioButtonMenuItem1) {
        this.jRadioButtonMenuItem1 = jRadioButtonMenuItem1;
    }

    public JLabel getLbl_busca() {
        return lbl_busca;
    }

    public void setLbl_busca(JLabel lbl_busca) {
        this.lbl_busca = lbl_busca;
    }

    public JLabel getLbl_filtro() {
        return lbl_filtro;
    }

    public void setLbl_filtro(JLabel lbl_filtro) {
        this.lbl_filtro = lbl_filtro;
    }

    public JLabel getLbl_historico() {
        return lbl_historico;
    }

    public void setLbl_historico(JLabel lbl_historico) {
        this.lbl_historico = lbl_historico;
    }

    public JLabel getLbl_perfil() {
        return lbl_perfil;
    }

    public void setLbl_perfil(JLabel lbl_perfil) {
        this.lbl_perfil = lbl_perfil;
    }

    public JLabel getLbl_playlists() {
        return lbl_playlists;
    }

    public void setLbl_playlists(JLabel lbl_playlists) {
        this.lbl_playlists = lbl_playlists;
    }

    public JLabel getLbl_nome() {
        return lbl_nome;
    }

    public void setLbl_nome(JLabel lbl_nome) {
        this.lbl_nome = lbl_nome;
    }

    public JLabel getLbl_welcome() {
        return lbl_welcome;
    }

    public void setLbl_welcome(JLabel lbl_welcome) {
        this.lbl_welcome = lbl_welcome;
    }

    public JTextField getTxt_busca() {
        return txt_busca;
    }

    public void setTxt_busca(JTextField txt_busca) {
        this.txt_busca = txt_busca;
    }

    public JComboBox<String> getCombobox_filtro() {
        return combobox_filtro;
    }

    public void setCombobox_filtro(JComboBox<String> combobox_filtro) {
        this.combobox_filtro = combobox_filtro;
    }

    public JTable getTabela() {
        return tabela;
    }

    public void setTabela(JTable tabela) {
        this.tabela = tabela;
    }

    
    
    
    
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jMenu1 = new javax.swing.JMenu();
        lbl_welcome = new javax.swing.JLabel();
        lbl_playlists = new javax.swing.JLabel();
        lbl_historico = new javax.swing.JLabel();
        txt_busca = new javax.swing.JTextField();
        bt_buscar = new javax.swing.JButton();
        lbl_busca = new javax.swing.JLabel();
        lbl_filtro = new javax.swing.JLabel();
        lbl_perfil = new javax.swing.JLabel();
        lbl_nome = new javax.swing.JLabel();
        combobox_filtro = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        lbl_musicas_curtidas = new javax.swing.JLabel();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Home");
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        lbl_welcome.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        lbl_welcome.setText("Boas-vindas, ");

        lbl_playlists.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lbl_playlists.setText("Playlists");
        lbl_playlists.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_playlists.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_playlistsMouseClicked(evt);
            }
        });

        lbl_historico.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lbl_historico.setText("Histórico");
        lbl_historico.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_historico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_historicoMouseClicked(evt);
            }
        });

        txt_busca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_buscaActionPerformed(evt);
            }
        });
        txt_busca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_buscaKeyPressed(evt);
            }
        });

        bt_buscar.setText("buscar");
        bt_buscar.setToolTipText("");
        bt_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_buscarActionPerformed(evt);
            }
        });

        lbl_busca.setText("busca");

        lbl_filtro.setText("filtro");

        lbl_perfil.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lbl_perfil.setText("Perfil");
        lbl_perfil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_perfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_perfilMouseClicked(evt);
            }
        });

        lbl_nome.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_nome.setText("NOME");

        combobox_filtro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "musica", "album", "artista", "genero" }));
        combobox_filtro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combobox_filtroActionPerformed(evt);
            }
        });

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Música", "Artista", "Álbum", "Gênero", "Duração", "Curtida", "Id_musica"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tabela);

        lbl_musicas_curtidas.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lbl_musicas_curtidas.setText("Músicas curtidas");
        lbl_musicas_curtidas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_musicas_curtidas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_musicas_curtidasMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_historico)
                    .addComponent(lbl_playlists)
                    .addComponent(lbl_perfil)
                    .addComponent(lbl_musicas_curtidas))
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_welcome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_nome))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lbl_busca)
                                    .addGap(0, 0, Short.MAX_VALUE))
                                .addComponent(txt_busca))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(combobox_filtro, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(bt_buscar))
                                .addComponent(lbl_filtro)))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 684, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_perfil)
                        .addGap(92, 92, 92)
                        .addComponent(lbl_musicas_curtidas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_playlists)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_historico))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_welcome)
                        .addComponent(lbl_nome))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_filtro)
                            .addComponent(lbl_busca))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(combobox_filtro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_busca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt_buscar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(98, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    private void txt_buscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_buscaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_buscaActionPerformed

    private void lbl_perfilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_perfilMouseClicked
        Usuario usuario2 = new Usuario(user,nome,senha);
        c.redirectPerfil(usuario2);
        
        //Perfil p = new Perfil();
        //p.setVisible(true);
        //this.setVisible(false);
        
    }//GEN-LAST:event_lbl_perfilMouseClicked

    private void lbl_playlistsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_playlistsMouseClicked
//        Playlist pl = new Playlist();
//        pl.setVisible(true);
//        this.setVisible(false);
            Usuario usuario2 = new Usuario(user,nome,senha);
          c.redirectPlaylist(usuario2);
    }//GEN-LAST:event_lbl_playlistsMouseClicked

    private void lbl_historicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_historicoMouseClicked
        
        //lbl_user.getLbl_user();
        Usuario usuario2 = new Usuario(user,nome,senha);
        c.redirectHistorico(usuario2);
        
//        Historico h = new Historico();
//        h.setVisible(true);
//        this.setVisible(false);
    }//GEN-LAST:event_lbl_historicoMouseClicked

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == evt.VK_H){
            
            
            
            Historico h = new Historico();
            h.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_formKeyPressed

    private void combobox_filtroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combobox_filtroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combobox_filtroActionPerformed

    private void bt_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_buscarActionPerformed
        // TODO add your handling code here:
        Usuario usuario2 = new Usuario(user,nome,senha);
        c.buscar(usuario2);
    }//GEN-LAST:event_bt_buscarActionPerformed

    private void txt_buscaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_buscaKeyPressed
        if(evt.getKeyCode() == evt.VK_ENTER){
            Usuario usuario2 = new Usuario(user,nome,senha);
            c.buscar(usuario2);            
        }
    }//GEN-LAST:event_txt_buscaKeyPressed

    private void lbl_musicas_curtidasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_musicas_curtidasMouseClicked
        Usuario usuario2 = new Usuario(user,nome,senha);
        c.redirectMusicasCurtidas(usuario2);
    }//GEN-LAST:event_lbl_musicas_curtidasMouseClicked

    
    
    
    
    
    
    
    
    
    

    
    
    
    
    
    

class ButtonRenderer extends JButton implements TableCellRenderer {
    public ButtonRenderer() {
        setOpaque(true);
    }

    public Component getTableCellRendererComponent(JTable table, Object value,
            boolean isSelected, boolean hasFocus, int row, int column) {
        setText((value == null) ? "Curtir" : value.toString());
        return this;
    }
}

class ButtonEditor extends DefaultCellEditor {
    private JButton button;
    private String label;
    private boolean clicked;
    private JTable table;

    public ButtonEditor(JCheckBox checkBox, JTable table) {
        super(checkBox);
        this.table = table;
        button = new JButton();
        button.setOpaque(true);

        button.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                fireEditingStopped();
            }
        });
    }

    public Component getTableCellEditorComponent(JTable table, Object value,
            boolean isSelected, int row, int column) {
        label = (value == null) ? "Curtir" : value.toString();
        button.setText(label);
        clicked = true;
        return button;
    }

    public Object getCellEditorValue() {
        if (clicked) {
            // Aqui você trata o clique no botão
            String musica = table.getValueAt(table.getSelectedRow(), 0).toString();
            JOptionPane.showMessageDialog(button, "Você curtiu: " + musica);
            // Você pode mudar o texto do botão para "Descurtir", por exemplo:
            label = label.equals("Curtir") ? "Descurtir" : "Curtir";
        }
        clicked = false;
        return label;
    }

    public boolean stopCellEditing() {
        clicked = false;
        return super.stopCellEditing();
    }

    protected void fireEditingStopped() {
        super.fireEditingStopped();
    }
}

    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Home().setVisible(true);
//            }
//        });
//    }
    
    private ControleHome c;
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_buscar;
    private javax.swing.JComboBox<String> combobox_filtro;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_busca;
    private javax.swing.JLabel lbl_filtro;
    private javax.swing.JLabel lbl_historico;
    private javax.swing.JLabel lbl_musicas_curtidas;
    private javax.swing.JLabel lbl_nome;
    private javax.swing.JLabel lbl_perfil;
    private javax.swing.JLabel lbl_playlists;
    private javax.swing.JLabel lbl_welcome;
    private javax.swing.JTable tabela;
    private javax.swing.JTextField txt_busca;
    // End of variables declaration//GEN-END:variables
}
