
package View;

import javax.swing.JLabel;
import Controller.ControlePerfil;
import Model.Usuario;


public class Perfil extends javax.swing.JFrame {
    
    private String user, nome, senha;

    public Perfil() {
        initComponents();
        c = new ControlePerfil(this);
    }
    
    public Perfil(Usuario usuario){
        initComponents();
        user = usuario.getUsuario();
        nome = usuario.getNome();
        senha = usuario.getSenha();
        lbl_user.setText(user);       
        lbl_nome.setText(nome);       
        c = new ControlePerfil(this);
    }   
    
    public JLabel getLbl_editar_perfil() {
        return lbl_editar_perfil;
    }

    public void setLbl_editar_perfil(JLabel lbl_editar_perfil) {
        this.lbl_editar_perfil = lbl_editar_perfil;
    }

    public JLabel getLbl_excluir_conta() {
        return lbl_excluir_conta;
    }

    public void setLbl_excluir_conta(JLabel lbl_excluir_conta) {
        this.lbl_excluir_conta = lbl_excluir_conta;
    }

    public JLabel getLbl_nome() {
        return lbl_nome;
    }

    public void setLbl_nome(JLabel lbl_nome) {
        this.lbl_nome = lbl_nome;
    }

    public JLabel getLbl_user() {
        return lbl_user;
    }

    public void setLbl_user(JLabel lbl_user) {
        this.lbl_user = lbl_user;
    }

    public JLabel getLbl_voltar() {
        return lbl_voltar;
    }

    public void setLbl_voltar(JLabel lbl_voltar) {
        this.lbl_voltar = lbl_voltar;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_nome = new javax.swing.JLabel();
        lbl_editar_perfil = new javax.swing.JLabel();
        lbl_excluir_conta = new javax.swing.JLabel();
        lbl_voltar = new javax.swing.JLabel();
        lbl_user = new javax.swing.JLabel();
        lbl_colchete_esquerda = new javax.swing.JLabel();
        lbl_colchete_direita = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Profile");

        lbl_nome.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lbl_nome.setText("NOME");

        lbl_editar_perfil.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lbl_editar_perfil.setText(" Editar perfil ");
        lbl_editar_perfil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_editar_perfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_editar_perfilMouseClicked(evt);
            }
        });

        lbl_excluir_conta.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lbl_excluir_conta.setForeground(new java.awt.Color(204, 0, 0));
        lbl_excluir_conta.setText("Excluir conta");
        lbl_excluir_conta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_excluir_conta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_excluir_contaMouseClicked(evt);
            }
        });

        lbl_voltar.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lbl_voltar.setText("←");
        lbl_voltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_voltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_voltarMouseClicked(evt);
            }
        });

        lbl_user.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lbl_user.setText("USER");

        lbl_colchete_esquerda.setText("[");

        lbl_colchete_direita.setText("]");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lbl_voltar)
                .addGap(94, 94, 94)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_colchete_esquerda)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_user)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_colchete_direita))
                    .addComponent(lbl_nome))
                .addContainerGap(130, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_editar_perfil)
                    .addComponent(lbl_excluir_conta))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(lbl_voltar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(lbl_nome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_user)
                            .addComponent(lbl_colchete_esquerda)
                            .addComponent(lbl_colchete_direita))))
                .addGap(129, 129, 129)
                .addComponent(lbl_editar_perfil)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_excluir_conta)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_voltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_voltarMouseClicked
        Usuario usuario2 = new Usuario(user,nome,senha);
        c.redirectPaginaHome(usuario2);            
    }//GEN-LAST:event_lbl_voltarMouseClicked

    private void lbl_excluir_contaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_excluir_contaMouseClicked
        Usuario usuario2 = new Usuario(user,nome,senha);
        c.excluirConta(usuario2);
    }//GEN-LAST:event_lbl_excluir_contaMouseClicked

    private void lbl_editar_perfilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_editar_perfilMouseClicked
        Usuario usuario2 = new Usuario(user,nome,senha);
        c.redirectEditarPerfil(usuario2);
    }//GEN-LAST:event_lbl_editar_perfilMouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Perfil().setVisible(true);
//            }
//        });
//    }
    
    private ControlePerfil c;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbl_colchete_direita;
    private javax.swing.JLabel lbl_colchete_esquerda;
    private javax.swing.JLabel lbl_editar_perfil;
    private javax.swing.JLabel lbl_excluir_conta;
    private javax.swing.JLabel lbl_nome;
    private javax.swing.JLabel lbl_user;
    private javax.swing.JLabel lbl_voltar;
    // End of variables declaration//GEN-END:variables
}
